FROM alpine:latest

MAINTAINER Martin Saidl, martin.saidl@tone.cz

ENV DATA_DIR=/config/data
ENV BIN_DIR=/config/bin
ENV CRON_DIR=/config/cron.d

RUN apk update --no-cache
RUN apk add --no-cache bash netcat-openbsd mtr jo jq ca-certificates

COPY scripts/entrypoint-probe.sh /sbin/entrypoint.sh
RUN chmod +x /sbin/entrypoint.sh

ENTRYPOINT ["sh", "/sbin/entrypoint.sh"]
